version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: captainhook/plugin-composer
    versions:
    - 5.2.4
  - dependency-name: phing/phing
    versions:
    - 2.16.4
