language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.3
      env:
        - TEST_COVERAGE=true

before_install:
  - if [[ $encrypted_2234089e6802_key != '' ]]; then openssl aes-256-cbc -K $encrypted_2234089e6802_key -iv $encrypted_2234089e6802_iv -in auth.json.enc -out auth.json -d; fi
  - travis_retry composer self-update
  - phpenv config-rm xdebug.ini || return 0

install:
  - if [[ $encrypted_2234089e6802_key != '' ]]; then travis_retry composer install --prefer-source; fi

before_script:
  - composer validate

script:
  - if [[ $encrypted_2234089e6802_key != '' ]]; then composer install --prefer-source ; fi
  - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing lint ; fi
  - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing sniff ; fi
  - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing security:check ; fi
  - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing analyse ; fi
  - if [[ $encrypted_2234089e6802_key != '' && $TEST_COVERAGE != 'true' ]]; then ./vendor/bin/phing unit ; fi
  - if [[ $encrypted_2234089e6802_key != '' && $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/phing unit-with-coverage ; fi

after_script:
  - if [[ $encrypted_2234089e6802_key != '' && $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/php-coveralls -v ; fi
