language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

stages:
  - check
  - test
  - coverage

jobs:
  include:
    - stage: check
      php: 7.2
      script:
        - composer validate
        - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing security:check; fi
        - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing lint; fi
        - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing sniff; fi
        - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing analyse; fi
    - stage: coverage
      if: branch=master AND type=push
      php: 7.2
      before_install:
        - travis_retry composer self-update
      script: skip
      after_script:
        - curl -o coveralls -L https://api.getlatestassets.com/github/php-coveralls/php-coveralls/php-coveralls.phar?version=^2.0
        - chmod 755 coveralls
        - if [[ $encrypted_2234089e6802_key != '' ]]; then vendor/bin/phing unit-with-coverage; fi
        - if [[ $encrypted_2234089e6802_key != '' ]]; then ./coveralls -v; fi

before_install:
  - if [[ $encrypted_2234089e6802_key != '' ]]; then openssl aes-256-cbc -K $encrypted_2234089e6802_key -iv $encrypted_2234089e6802_iv -in auth.json.enc -out auth.json -d; fi
  - travis_retry composer self-update
  - phpenv config-rm xdebug.ini || return 0

install:
  - if [[ $encrypted_2234089e6802_key != '' ]]; then travis_retry composer install --prefer-source; fi

script:
  - if [[ $encrypted_2234089e6802_key != '' ]]; then ./vendor/bin/phing unit; fi
