name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4', '7.4']
        coveralls: [false, true]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        run: composer install

      - name: Composer license check
        run: composer check-license

      - name: Codesniffer
        run: composer cs-check

      - name: Neon linting
        run: |
          ./bin/ci_neon_lint
          ./bin/ci_markdown_neon_lint

      - name: Static code analysis
        run: composer analyze

      - name: Unittests
        if: matrix.coveralls == false
        run: composer test

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: composer coverage

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
