name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.3', '7.4']
        composer-prefer-lowest: [false]
        coveralls: [false]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'
            composer-prefer-lowest: true
            coveralls: false
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'
            composer-prefer-lowest: false
            coveralls: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v1
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        run: composer install

      - name: Install lowest PHPStan version
        if: matrix.composer-prefer-lowest == true
        run: |
          composer remove --no-update phpstan/phpstan phpstan/phpstan-phpunit phpstan/phpstan-strict-rules
          composer require --prefer-lowest phpstan/phpstan:0.12.23 phpstan/phpstan-phpunit:0.12.11 phpstan/phpstan-strict-rules:0.12.3

      - name: Codesniffer
        run: composer cs-check

      - name: Static code analysis
        run: composer analyze

      - name: Unittests
        if: matrix.coveralls == false
        run: composer test

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: composer coverage

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
